#[cfg(test)]
mod tests {
    use soroban_sdk::{
        testutils::{Address as _, Events},
        symbol_short, Address, Env, Symbol,
    };

    // Import the contract and its client (auto-generated by soroban-sdk)
    use crate::{PayScriptContract, PayScriptContractClient};

    // ─────────────────────────────────────────────────────────────────
    // SHARED SETUP HELPER
    // Deploys the contract and returns (env, client, admin, developer, buyer)
    // so each test starts from a clean, initialized state.
    // ─────────────────────────────────────────────────────────────────
    fn setup() -> (Env, PayScriptContractClient<'static>, Address, Address, Address) {
        let env = Env::default();
        env.mock_all_auths(); // Mock all auth checks so tests focus on logic

        let contract_id = env.register_contract(None, PayScriptContract);
        let client = PayScriptContractClient::new(&env, &contract_id);

        let admin     = Address::generate(&env);
        let developer = Address::generate(&env);
        let buyer     = Address::generate(&env);

        // Initialize contract with admin
        client.initialize(&admin);

        (env, client, admin, developer, buyer)
    }

    // ─────────────────────────────────────────────────────────────────
    // TEST 1 — HAPPY PATH
    // Full MVP transaction: developer registers API, buyer purchases
    // credits, buyer verifies access and credits are deducted correctly.
    // ─────────────────────────────────────────────────────────────────
    #[test]
    fn test_happy_path_full_mvp_flow() {
        let (env, client, _admin, developer, buyer) = setup();

        let api_key: Symbol = symbol_short!("MYAPI");
        let price_per_call: i128 = 100_000; // 0.01 XLM per call
        let amount_paid: i128 = 1_000_000; // 0.1 XLM = 10 credits

        // Step 1: Developer registers their API
        client.register_api(&developer, &api_key, &price_per_call);

        // Step 2: Buyer purchases credits
        client.purchase_credits(&buyer, &api_key, &amount_paid);

        // Step 3: Verify buyer received exactly 10 credits
        let credits = client.get_credits(&buyer);
        assert_eq!(credits, 10, "Buyer should have 10 credits after paying 0.1 XLM at 0.01 XLM/call");

        // Step 4: Buyer uses one credit to access the API
        let access_granted = client.verify_access(&buyer, &api_key);
        assert!(access_granted, "Access should be granted when credits exist");

        // Step 5: Verify credit was deducted
        let remaining = client.get_credits(&buyer);
        assert_eq!(remaining, 9, "One credit should be deducted after API access");
    }

    // ─────────────────────────────────────────────────────────────────
    // TEST 2 — EDGE CASE: ACCESS DENIED WITH ZERO CREDITS
    // A buyer who has never purchased credits (or has used them all)
    // must be denied access. This tests the authorization guard.
    // ─────────────────────────────────────────────────────────────────
    #[test]
    #[should_panic(expected = "no credits remaining")]
    fn test_access_denied_with_zero_credits() {
        let (env, client, _admin, developer, buyer) = setup();

        let api_key: Symbol = symbol_short!("MYAPI");

        // Developer registers API
        client.register_api(&developer, &api_key, &100_000_i128);

        // Buyer never purchased credits — verify_access should panic
        client.verify_access(&buyer, &api_key);
    }

    // ─────────────────────────────────────────────────────────────────
    // TEST 3 — STATE VERIFICATION
    // After a purchase, assert that both the credit balance AND the
    // revenue counter are stored correctly in contract state.
    // ─────────────────────────────────────────────────────────────────
    #[test]
    fn test_state_correct_after_purchase() {
        let (env, client, _admin, developer, buyer) = setup();

        let api_key: Symbol = symbol_short!("TESTAPI");
        let price_per_call: i128 = 500_000; // 0.05 XLM per call
        let amount_paid: i128 = 2_500_000; // 0.25 XLM = 5 credits

        client.register_api(&developer, &api_key, &price_per_call);
        client.purchase_credits(&buyer, &api_key, &amount_paid);

        // Assert credits are stored correctly
        let credits = client.get_credits(&buyer);
        assert_eq!(credits, 5, "State: buyer should have 5 credits");

        // Assert revenue counter is updated correctly
        let revenue = client.get_revenue(&api_key);
        assert_eq!(revenue, 2_500_000, "State: API revenue should equal amount paid");

        // Assert price is stored correctly
        let price = client.get_price(&api_key);
        assert_eq!(price, 500_000, "State: price per call should be stored correctly");
    }

    // ─────────────────────────────────────────────────────────────────
    // TEST 4 — EDGE CASE: INSUFFICIENT PAYMENT
    // Buyer sends less XLM than the price of a single call.
    // Contract should panic rather than issue fractional credits.
    // ─────────────────────────────────────────────────────────────────
    #[test]
    #[should_panic(expected = "insufficient payment")]
    fn test_insufficient_payment_rejected() {
        let (env, client, _admin, developer, buyer) = setup();

        let api_key: Symbol = symbol_short!("PRICEAPI");
        let price_per_call: i128 = 1_000_000; // 0.1 XLM per call

        client.register_api(&developer, &api_key, &price_per_call);

        // Buyer only sends 0.05 XLM — not enough for a single credit
        let underpayment: i128 = 500_000;
        client.purchase_credits(&buyer, &api_key, &underpayment);
    }

    // ─────────────────────────────────────────────────────────────────
    // TEST 5 — CREDITS ACCUMULATE ACROSS MULTIPLE PURCHASES
    // A buyer who purchases credits twice should have their balances
    // combined correctly, simulating a real top-up flow.
    // ─────────────────────────────────────────────────────────────────
    #[test]
    fn test_credits_accumulate_across_purchases() {
        let (env, client, _admin, developer, buyer) = setup();

        let api_key: Symbol = symbol_short!("TOPUPAPI");
        let price_per_call: i128 = 100_000; // 0.01 XLM per call

        client.register_api(&developer, &api_key, &price_per_call);

        // First purchase: 0.1 XLM = 10 credits
        client.purchase_credits(&buyer, &api_key, &1_000_000_i128);
        let after_first = client.get_credits(&buyer);
        assert_eq!(after_first, 10, "Should have 10 credits after first purchase");

        // Second purchase (top-up): 0.05 XLM = 5 more credits
        client.purchase_credits(&buyer, &api_key, &500_000_i128);
        let after_second = client.get_credits(&buyer);
        assert_eq!(after_second, 15, "Credits should accumulate: 10 + 5 = 15");

        // Total revenue should reflect both purchases
        let total_revenue = client.get_revenue(&api_key);
        assert_eq!(total_revenue, 1_500_000, "Revenue should be sum of both payments");
    }
}